openapi: 3.2.0
info:
  title: AdminWeb Filters API
  version: '1.0'
tags:
- name: Filters
paths:
  /LoadIsActiveSelectList:
    post:
      tags:
      - Filters
      parameters:
      - name: Search
        in: query
        schema:
          type: string
      - name: Values
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
      summary: Create load is active select list
      x-summary-source: derived
      operationId: postLoadIsActiveSelectList
      x-operation-id-source: derived
  /LoadRolesSelectList:
    post:
      tags:
      - Filters
      parameters:
      - name: Search
        in: query
        schema:
          type: string
      - name: Values
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
      summary: Create load roles select list
      x-summary-source: derived
      operationId: postLoadRolesSelectList
      x-operation-id-source: derived
  /LoadDeviceAzureSelectList:
    post:
      tags:
      - Filters
      parameters:
      - name: Search
        in: query
        schema:
          type: string
      - name: Values
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
      summary: Create load device azure select list
      x-summary-source: derived
      operationId: postLoadDeviceAzureSelectList
      x-operation-id-source: derived
  /LoadDeviceAzureNotBindedSelectList:
    post:
      tags:
      - Filters
      parameters:
      - name: Search
        in: query
        schema:
          type: string
      - name: Values
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
      summary: Create load device azure not binded select list
      x-summary-source: derived
      operationId: postLoadDeviceAzureNotBindedSelectList
      x-operation-id-source: derived
  /LoadProductTypeSelectList:
    post:
      tags:
      - Filters
      parameters:
      - name: Search
        in: query
        schema:
          type: string
      - name: Values
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
      summary: Create load product type select list
      x-summary-source: derived
      operationId: postLoadProductTypeSelectList
      x-operation-id-source: derived
  /LoadOrganizationTypeSelectList:
    post:
      tags:
      - Filters
      parameters:
      - name: Search
        in: query
        schema:
          type: string
      - name: Values
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
      summary: Create load organization type select list
      x-summary-source: derived
      operationId: postLoadOrganizationTypeSelectList
      x-operation-id-source: derived
  /LoadOrganizationStatusSelectList:
    post:
      tags:
      - Filters
      parameters:
      - name: Search
        in: query
        schema:
          type: string
      - name: Values
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
      summary: Create load organization status select list
      x-summary-source: derived
      operationId: postLoadOrganizationStatusSelectList
      x-operation-id-source: derived
  /LoadOrganizationSelectList:
    post:
      tags:
      - Filters
      parameters:
      - name: IsAllOrgs
        in: query
        schema:
          type: boolean
      - name: Search
        in: query
        schema:
          type: string
      - name: Values
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
      summary: Create load organization select list
      x-summary-source: derived
      operationId: postLoadOrganizationSelectList
      x-operation-id-source: derived
  /LoadDeviceStatusList:
    post:
      tags:
      - Filters
      parameters:
      - name: Search
        in: query
        schema:
          type: string
      - name: Values
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
      summary: Create load device status list
      x-summary-source: derived
      operationId: postLoadDeviceStatusList
      x-operation-id-source: derived
  /LoadColorCodingStatusList:
    post:
      tags:
      - Filters
      parameters:
      - name: Search
        in: query
        schema:
          type: string
      - name: Values
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
      summary: Create load color coding status list
      x-summary-source: derived
      operationId: postLoadColorCodingStatusList
      x-operation-id-source: derived
  /LoadDevicesSelectList:
    post:
      tags:
      - Filters
      parameters:
      - name: SelectedOrganizationIds
        in: query
        schema:
          type: string
      - name: SelectedDeviceIds
        in: query
        schema:
          type: string
      - name: Search
        in: query
        schema:
          type: string
      - name: Values
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
      summary: Create load devices select list
      x-summary-source: derived
      operationId: postLoadDevicesSelectList
      x-operation-id-source: derived
  /LoadDevicesSelectListArchiveDependent:
    post:
      tags:
      - Filters
      parameters:
      - name: SelectedOrganizationIds
        in: query
        schema:
          type: string
      - name: SelectedDeviceIds
        in: query
        schema:
          type: string
      - name: Search
        in: query
        schema:
          type: string
      - name: Values
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
      summary: Create load devices select list archive dependent
      x-summary-source: derived
      operationId: postLoadDevicesSelectListArchiveDependent
      x-operation-id-source: derived
  /LoadDevicesSelectListNotInLocation:
    post:
      tags:
      - Filters
      parameters:
      - name: SelectedOrganizationIds
        in: query
        schema:
          type: string
      - name: SelectedDeviceIds
        in: query
        schema:
          type: string
      - name: Search
        in: query
        schema:
          type: string
      - name: Values
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
      summary: Create load devices select list not in location
      x-summary-source: derived
      operationId: postLoadDevicesSelectListNotInLocation
      x-operation-id-source: derived
  /LoadDevicesSelectListNotInOrganization:
    post:
      tags:
      - Filters
      parameters:
      - name: Search
        in: query
        schema:
          type: string
      - name: Values
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
      summary: Create load devices select list not in organization
      x-summary-source: derived
      operationId: postLoadDevicesSelectListNotInOrganization
      x-operation-id-source: derived
  /LoadAlertTypeSelectList:
    post:
      tags:
      - Filters
      parameters:
      - name: Search
        in: query
        schema:
          type: string
      - name: Values
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
      summary: Create load alert type select list
      x-summary-source: derived
      operationId: postLoadAlertTypeSelectList
      x-operation-id-source: derived
  /LoadAlertSettingsSelectList:
    post:
      tags:
      - Filters
      parameters:
      - name: Search
        in: query
        schema:
          type: string
      - name: Values
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
      summary: Create load alert settings select list
      x-summary-source: derived
      operationId: postLoadAlertSettingsSelectList
      x-operation-id-source: derived
  /LoadAlertTypeFilteredSelectList:
    post:
      tags:
      - Filters
      parameters:
      - name: Search
        in: query
        schema:
          type: string
      - name: Values
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
      summary: Create load alert type filtered select list
      x-summary-source: derived
      operationId: postLoadAlertTypeFilteredSelectList
      x-operation-id-source: derived
  /LoadAlertStatusSelectList:
    post:
      tags:
      - Filters
      parameters:
      - name: Search
        in: query
        schema:
          type: string
      - name: Values
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
      summary: Create load alert status select list
      x-summary-source: derived
      operationId: postLoadAlertStatusSelectList
      x-operation-id-source: derived
  /LoadUsersSelectList:
    post:
      tags:
      - Filters
      parameters:
      - name: SelectedOrganizationIds
        in: query
        schema:
          type: string
      - name: Search
        in: query
        schema:
          type: string
      - name: Values
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
      summary: Create load users select list
      x-summary-source: derived
      operationId: postLoadUsersSelectList
      x-operation-id-source: derived
  /LoadTelemetryTypesSelectList:
    post:
      tags:
      - Filters
      parameters:
      - name: Search
        in: query
        schema:
          type: string
      - name: Values
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
      summary: Create load telemetry types select list
      x-summary-source: derived
      operationId: postLoadTelemetryTypesSelectList
      x-operation-id-source: derived
  /LoadSettingLayerTypesSelectList:
    post:
      tags:
      - Filters
      parameters:
      - name: Search
        in: query
        schema:
          type: string
      - name: Values
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
      summary: Create load setting layer types select list
      x-summary-source: derived
      operationId: postLoadSettingLayerTypesSelectList
      x-operation-id-source: derived
  /LoadConfigChangeTypeSelectList:
    post:
      tags:
      - Filters
      parameters:
      - name: Search
        in: query
        schema:
          type: string
      - name: Values
        in: query
        schema:
          type: string
      responses:
        '200':
          description: OK
      summary: Create load config change type select list
      x-summary-source: derived
      operationId: postLoadConfigChangeTypeSelectList
      x-operation-id-source: derived
