openapi: 3.2.0
info:
  title: AdminWeb Organization API
  version: '1.0'
tags:
- name: Organization
paths:
  /LoadLocationsByOrgId:
    post:
      tags:
      - Organization
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/ObjId'
          application/json:
            schema:
              $ref: '#/components/schemas/ObjId'
          text/json:
            schema:
              $ref: '#/components/schemas/ObjId'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ObjId'
      responses:
        '200':
          description: OK
      summary: Create load locations by org id
      x-summary-source: derived
      operationId: postLoadLocationsByOrgId
      x-operation-id-source: derived
components:
  schemas:
    ObjId:
      type: object
      properties:
        id:
          type: string
          format: uuid
      additionalProperties: false
