openapi: 3.2.0
info:
  title: AdminWeb Files API
  version: '1.0'
tags:
- name: Files
paths:
  /UploadFile:
    post:
      tags:
      - Files
      parameters:
      - name: id
        in: query
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
            encoding:
              file:
                style: form
      responses:
        '200':
          description: OK
      summary: Create upload file
      x-summary-source: derived
      operationId: postUploadFile
      x-operation-id-source: derived
  /DownloadFile:
    get:
      tags:
      - Files
      parameters:
      - name: id
        in: query
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: OK
      summary: Get download file
      x-summary-source: derived
      operationId: getDownloadFile
      x-operation-id-source: derived
  /DeleteFile:
    post:
      tags:
      - Files
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/ObjId'
          application/json:
            schema:
              $ref: '#/components/schemas/ObjId'
          text/json:
            schema:
              $ref: '#/components/schemas/ObjId'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ObjId'
      responses:
        '200':
          description: OK
      summary: Create delete file
      x-summary-source: derived
      operationId: postDeleteFile
      x-operation-id-source: derived
components:
  schemas:
    ObjId:
      type: object
      properties:
        id:
          type: string
          format: uuid
      additionalProperties: false
