openapi: 3.2.0
info:
  title: AdminWeb Client API
  version: '1.0'
tags:
- name: Client
paths:
  /GetClientCountryCodeByIp:
    get:
      tags:
      - Client
      responses:
        '200':
          description: OK
      summary: Get get client country code by ip
      x-summary-source: derived
      operationId: getGetClientCountryCodeByIp
      x-operation-id-source: derived
