openapi: 3.2.0
info:
  title: AdminWeb Alert API
  version: '1.0'
tags:
- name: Alert
paths:
  /LoadRecipients:
    post:
      tags:
      - Alert
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/ObjId'
          application/json:
            schema:
              $ref: '#/components/schemas/ObjId'
          text/json:
            schema:
              $ref: '#/components/schemas/ObjId'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ObjId'
      responses:
        '200':
          description: OK
      summary: Create load recipients
      x-summary-source: derived
      operationId: postLoadRecipients
      x-operation-id-source: derived
  /LoadAlertSetting:
    post:
      tags:
      - Alert
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/ObjId'
          application/json:
            schema:
              $ref: '#/components/schemas/ObjId'
          text/json:
            schema:
              $ref: '#/components/schemas/ObjId'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ObjId'
      responses:
        '200':
          description: OK
      summary: Create load alert setting
      x-summary-source: derived
      operationId: postLoadAlertSetting
      x-operation-id-source: derived
  /LoadAlertSettingDetails:
    post:
      tags:
      - Alert
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/ObjId'
          application/json:
            schema:
              $ref: '#/components/schemas/ObjId'
          text/json:
            schema:
              $ref: '#/components/schemas/ObjId'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ObjId'
      responses:
        '200':
          description: OK
      summary: Create load alert setting details
      x-summary-source: derived
      operationId: postLoadAlertSettingDetails
      x-operation-id-source: derived
  /LoadAlertTypeInfo:
    post:
      tags:
      - Alert
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/ObjId'
          application/json:
            schema:
              $ref: '#/components/schemas/ObjId'
          text/json:
            schema:
              $ref: '#/components/schemas/ObjId'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ObjId'
      responses:
        '200':
          description: OK
      summary: Create load alert type info
      x-summary-source: derived
      operationId: postLoadAlertTypeInfo
      x-operation-id-source: derived
components:
  schemas:
    ObjId:
      type: object
      properties:
        id:
          type: string
          format: uuid
      additionalProperties: false
