openapi: 3.2.0
info:
  title: AdminWeb Permissions API
  version: '1.0'
tags:
- name: Permissions
paths:
  /GetPermissions:
    post:
      tags:
      - Permissions
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/PermissionsReq'
          application/json:
            schema:
              $ref: '#/components/schemas/PermissionsReq'
          text/json:
            schema:
              $ref: '#/components/schemas/PermissionsReq'
          application/*+json:
            schema:
              $ref: '#/components/schemas/PermissionsReq'
      responses:
        '200':
          description: OK
      summary: Create get permissions
      x-summary-source: derived
      operationId: postGetPermissions
      x-operation-id-source: derived
  /LoadRolesForUser:
    post:
      tags:
      - Permissions
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/RolesForUserReq'
          application/json:
            schema:
              $ref: '#/components/schemas/RolesForUserReq'
          text/json:
            schema:
              $ref: '#/components/schemas/RolesForUserReq'
          application/*+json:
            schema:
              $ref: '#/components/schemas/RolesForUserReq'
      responses:
        '200':
          description: OK
      summary: Create load roles for user
      x-summary-source: derived
      operationId: postLoadRolesForUser
      x-operation-id-source: derived
  /SwitchOrganization:
    post:
      tags:
      - Permissions
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/ObjIdNullable'
          application/json:
            schema:
              $ref: '#/components/schemas/ObjIdNullable'
          text/json:
            schema:
              $ref: '#/components/schemas/ObjIdNullable'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ObjIdNullable'
      responses:
        '200':
          description: OK
      summary: Create switch organization
      x-summary-source: derived
      operationId: postSwitchOrganization
      x-operation-id-source: derived
  /GetPermissionsForUser:
    post:
      tags:
      - Permissions
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/PermissionsReqForUser'
          application/json:
            schema:
              $ref: '#/components/schemas/PermissionsReqForUser'
          text/json:
            schema:
              $ref: '#/components/schemas/PermissionsReqForUser'
          application/*+json:
            schema:
              $ref: '#/components/schemas/PermissionsReqForUser'
      responses:
        '200':
          description: OK
      summary: Create get permissions for user
      x-summary-source: derived
      operationId: postGetPermissionsForUser
      x-operation-id-source: derived
components:
  schemas:
    ObjIdNullable:
      type: object
      properties:
        id:
          type:
          - string
          - 'null'
          format: uuid
      additionalProperties: false
    RolesForUserReq:
      type: object
      properties:
        id:
          type:
          - string
          - 'null'
          format: uuid
        selectedOrgIds:
          type:
          - array
          - 'null'
          items:
            type: string
      additionalProperties: false
    PermissionsReq:
      type: object
      properties:
        organizationTypeId:
          type:
          - string
          - 'null'
          format: uuid
        selectedRoles:
          type:
          - array
          - 'null'
          items:
            type: string
            format: uuid
        grantedPermissions:
          type:
          - array
          - 'null'
          items:
            type: integer
            format: int32
        deniedPermissions:
          type:
          - array
          - 'null'
          items:
            type: integer
            format: int32
      additionalProperties: false
    PermissionsReqForUser:
      type: object
      properties:
        userId:
          type:
          - string
          - 'null'
          format: uuid
        selectedRoles:
          type:
          - array
          - 'null'
          items:
            type: string
            format: uuid
        selectedOrgIds:
          type:
          - array
          - 'null'
          items:
            type: string
        grantedPermissions:
          type:
          - array
          - 'null'
          items:
            type: integer
            format: int32
        deniedPermissions:
          type:
          - array
          - 'null'
          items:
            type: integer
            format: int32
      additionalProperties: false
